apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: "davp-demo39-3-on-push"
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/pipelines/docker-build-tssc.yaml"
    pipelinesascode.tekton.dev/task-0: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/init.yaml"
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/git-clone.yaml"
    pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/buildah-rhtap.yaml"
    pipelinesascode.tekton.dev/task-3: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/acs-image-check.yaml"
    pipelinesascode.tekton.dev/task-4: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/acs-image-scan.yaml"
    pipelinesascode.tekton.dev/task-5: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/acs-deploy-check.yaml"
    pipelinesascode.tekton.dev/task-6: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/update-deployment.yaml"
    pipelinesascode.tekton.dev/task-7: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/show-sbom-rhdh.yaml"
    pipelinesascode.tekton.dev/task-8: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/summary.yaml"
    pipelinesascode.tekton.dev/task-9: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/build-workload.yaml"
    pipelinesascode.tekton.dev/task-10: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/deploy-workload.yaml"
    pipelinesascode.tekton.dev/task-11: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/scan-workload.yaml"
    pipelinesascode.tekton.dev/task-12: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/summarize-workload.yaml"
    pipelinesascode.tekton.dev/task-13: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/show-workload-sbom.yaml"
    pipelinesascode.tekton.dev/task-14: "https://raw.githubusercontent.com/dperaza4dustbit/tssc-dev-multi-ci/additional_piepline_warnings/samples/tekton/pac/tasks/deploy-workload-check.yaml"
  labels:
    argocd/app-name: davp-demo39-3
    janus-idp.io/tekton: davp-demo39-3
    backstage.io/kubernetes-id: davp-demo39-3
    backstage.io/kubernetes-namespace: tssc-app
    app.kubernetes.io/part-of: davp-demo39-3
spec:
  params:
    - name: dockerfile
      value: "src/main/docker/Dockerfile.jvm.staged"
    - name: git-url
      value: '{{repo_url}}'
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: "quay.io/tsscdavp/ssm-demo39-3:{{revision}}"
    - name: path-context
      value: "."
    - name: revision
      value: '{{revision}}'
    - name: event-type
      value: '{{event_type}}'
    - name: gitops-auth-secret-name
      value: "gitops-auth-secret"
  pipelineRef:
    name: docker-build-rhtap
  workspaces:
    - name: gitops-auth
      secret:
        secretName: "$(params.gitops-auth-secret-name)"
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
